check on running as root

diff --git a/worker/bin/canfar_batch_prepare b/worker/bin/canfar_batch_prepare
--- a/worker/bin/canfar_batch_prepare
+++ b/worker/bin/canfar_batch_prepare
@@ -1,10 +1,9 @@
 #!/bin/bash
 
 # Shell script to prepare a VM for batch at interactive time
-# avoid ruby/python bloat (puppet/chef/ansible) and replace with bash bloat :)
 
 EXEC_NAME=$(basename $0 .${0##*.})
-EXEC_VERSION=0.1.9
+EXEC_VERSION=0.2.0
 
 CONDOR_MIN_VERSION=8.8
 
@@ -13,7 +12,7 @@ msg() {
 }
 
 die() {
-    echo -e " >> ${EXEC_NAME} ERROR: $1" 1>&2
+    echo -e " !! ${EXEC_NAME} ERROR: $1" 1>&2
     exit 1
 }
 
@@ -165,6 +164,8 @@ while true; do
     esac
     shift
 done
+
+[[ ${EUID} -ne 0 ]] && die "you must run this script as root or with sudo"
 
 canfar_install_condor
 canfar_disable_selinux
