consistent format in error messages

diff --git a/worker/bin/canfar_batch_prepare b/worker/bin/canfar_batch_prepare
--- a/worker/bin/canfar_batch_prepare
+++ b/worker/bin/canfar_batch_prepare
@@ -8,11 +8,11 @@ EXEC_VERSION=0.1.5
 CONDOR_MIN_VERSION=8.6
 
 msg() {
-    echo " >> ${EXEC_NAME}: $1"
+    echo -e " >> ${EXEC_NAME}: $1"
 }
 
 die() {
-    echo "${EXEC_NAME} ERROR: $1" 1>&2
+    echo -e " >> ${EXEC_NAME} ERROR: $1" 1>&2
     exit 1
 }
 
diff --git a/worker/bin/canfar_cert b/worker/bin/canfar_cert
--- a/worker/bin/canfar_cert
+++ b/worker/bin/canfar_cert
@@ -25,11 +25,11 @@ CANFAR_URL="www.canfar.phys.uvic.ca"
 CANFAR_USER="${USER}"
 
 msg() {
-    echo " >> ${EXEC_NAME}: $1"
+    echo -e " >> ${EXEC_NAME}: $1"
 }
 
 die() {
-    echo "${EXEC_NAME} ERROR: $1" 1>&2
+    echo -e " >> ${EXEC_NAME} ERROR: $1" 1>&2
     exit 1
 }
 
diff --git a/worker/bin/canfar_create_user b/worker/bin/canfar_create_user
--- a/worker/bin/canfar_create_user
+++ b/worker/bin/canfar_create_user
@@ -4,11 +4,11 @@ EXEC_NAME=$(basename $0 .${0##*.})
 EXEC_VERSION=0.1.2
 
 msg() {
-    echo " >> ${EXEC_NAME}: $1"
+    echo -e " >> ${EXEC_NAME}: $1"
 }
 
 die() {
-    echo "${EXEC_NAME} ERROR: $1" 1>&2
+    echo -e " >> ${EXEC_NAME} ERROR: $1" 1>&2
     exit 1
 }
 
diff --git a/worker/bin/canfar_dotnetrc b/worker/bin/canfar_dotnetrc
--- a/worker/bin/canfar_dotnetrc
+++ b/worker/bin/canfar_dotnetrc
@@ -8,7 +8,7 @@ msg() {
 }
 
 die() {
-    echo "${EXEC_NAME} ERROR: $1" 1>&2
+    echo -e " >> ${EXEC_NAME} ERROR: $1" 1>&2
     exit 1
 }
 
