check on running as root

diff --git a/worker/bin/canfar_create_user b/worker/bin/canfar_create_user
--- a/worker/bin/canfar_create_user
+++ b/worker/bin/canfar_create_user
@@ -1,20 +1,20 @@
 #!/bin/bash
 
 EXEC_NAME=$(basename $0 .${0##*.})
-EXEC_VERSION=0.1.2
+EXEC_VERSION=0.1.3
 
 msg() {
     echo -e " >> ${EXEC_NAME}: $1"
 }
 
 die() {
-    echo -e " >> ${EXEC_NAME} ERROR: $1" 1>&2
+    echo -e " !! ERROR ${EXEC_NAME}: $1" 1>&2
     exit 1
 }
 
 usage() {
     echo $"Usage: ${EXEC_NAME} USERNAME
-Create a local user with propagated keys and sudo privileges. Run as sudo.
+Create a local user with propagated keys and sudo privileges
 
   -h, --help                display help and exit
   -v, --version             output version information and exit
@@ -23,7 +23,7 @@ Create a local user with propagated keys and sudo privileges. Run as sudo.
 }
 
 # create a user with sudo privs and ssh on the fly for debian or fedora based distros
-create_user() {
+create_vm_user() {
     local username=$1
     local sshdir=/home/${username}/.ssh
     useradd -m -s /bin/bash -d /home/${username} ${username} || die "failed to create user ${username}"
@@ -65,5 +65,6 @@ done
 
 [[ ${EUID} -ne 0 ]] && die "you must run this script as root or with sudo"
 username=$1
+
 [[ -z ${username} ]] && read -p "Enter the CANFAR username: " username
-create_user ${username} && msg "user ${username} created"
+create_vm_user ${username} && msg "user ${username} created with sudo privileges"
