use newer openstack clients

diff --git a/manager/bin/canfar_cloud_cleanup b/manager/bin/canfar_cloud_cleanup
--- a/manager/bin/canfar_cloud_cleanup
+++ b/manager/bin/canfar_cloud_cleanup
@@ -1,50 +1,76 @@
 #!/bin/bash
 
-VM_PREFIX="canfar-"
-CLOUD_NAME="canfar"
+EXEC_NAME=$(basename $0 .${0##*.})
+EXEC_VERSION=0.3.1
+
+msg() {
+    echo -e " >> ${EXEC_NAME}: $1"
+}
+
+warn() {
+    echo -e " ## WARNING ${EXEC_NAME}: $1"
+}
+
+die() {
+    echo -e " !! ERROR ${EXEC_NAME}: $1" 1>&2
+    exit 1
+}
+
+usage() {
+    echo $"Usage: ${EXEC_NAME} [cloud]
+Cleanup HTCondor with OpenStack cloud
+"
+    exit
+}
+
+cloud=$1
+
+source /mnt/stats/openstack/projects/${cloud/cc-}/CANFAR-openrc.sh
 
 export PATH="/usr/local/bin:${PATH}"
 
+log_file="/var/log/cloudcleanup.log"
+
 # loop on VM instance names found on nova
-for vm_name in $(nova list 2> /dev/null | grep "^|" | grep -v ID | grep ${VM_PREFIX} | awk '{print $4}'); do
+for vm_nova_name in $(openstack server list -f value -c Name 2> /dev/null | grep ${cloud}); do
     
     # check if cloud scheduler is tracking the VM
-    vm_cs=$(cloud_status -m | grep ${vm_name} | awk '{print $2}')
-    [ -n "${vm_cs}" ] && continue
+    vm_cs_name=$(cloud_status -m | grep ${vm_nova_name} | awk '{print $2}')
+    [[ -n "${vm_cs_name}" ]] && continue
 
-    echo "Lost instance ${vm_name} from cloud_scheduler"
-    vm_to_delete="${vm_to_delete} ${vm_name}"
+    msg "cloud_scheduler lost ${vm_nova_name}"
+    vm_to_delete="${vm_to_delete} ${vm_nova_name}"
 
     # if vm is still running condor, shutdown daemons peacefully first
-    vm_worker=$(condor_status -l -attributes Name | awk '{print $3}' | sed -e 's/"//g' | grep ${vm_name})
-    [ -z "${vm_worker}" ] && continue
+    vm_worker=$(condor_status -l -attributes Name | awk '{print $3}' | sed -e 's/"//g' | grep ${vm_nova_name})
+    [[ -z "${vm_worker}" ]] && continue
 
     condor_off -peaceful -name ${vm_worker} -startd
     # get startd and master IPs
     addr=$(condor_status ${vm_worker} -l | grep MyAddress | head -n1 | sed  -e 's/"//g')
     if  [ -n "${addr}" ]; then 
-	echo " > shutdown startd daemon ${startd_addr} on ${vm_name}"
+	msg "shutdown startd daemon ${startd_addr} on ${vm_nova_name}"
 	condor_off -peaceful -addr ${addr} -startd
     fi
     addr=$(condor_status ${vm_worker} -l -master | grep MasterIpAddr | sed -e 's/"//g')
-    if  [ -n "${addr}" ]; then 
-	echo " > shutdown master daemon ${addr} on ${vm_name}"
+    if  [[ -n "${addr}" ]]; then 
+	msg "shutdown master daemon ${addr} on ${vm_nova_name}"
 	condor_off -peaceful -addr ${addr} -master
     fi
 done
 
 # terminate all instances found on nova but not on cloud scheduler
 if [ -n "${vm_to_delete}" ]; then
-    echo "Terminating the $(echo ${vm_to_delete} | wc -w) instances lost from cloud scheduler"
-    nova delete ${VM_DELETE} 2> /dev/null
+    msg "deleting the $(echo ${vm_to_delete} | wc -w) instances lost from cloud scheduler"
+    openstack server delete ${vm_to_delete}
 fi
 
 # work around cloud scheduler threaded clean-up dead-lock
 bad_vms="$(cloud_status -m | grep Retiring | awk '{print $1}')"
-if [ -n "${bad_vms}" ]; then
-    for vm_cs in ${bad_vms}; do
-	echo "Terminating VM ${vm_cs} in Retiring state"
-	cloud_admin -k -n ${vm_cs} -c ${CLOUD_NAME}
+if [[ -n "${bad_vms}" ]]; then
+    for vm_cs_id in ${bad_vms}; do
+	msg "killing VM ID ${vm_cs_id} in Retiring state"
+	cloud_admin -k -n ${vm_cs_id} -c ${cloud}
     done
 fi
 
@@ -60,12 +86,15 @@ fi
 #    cloud_admin -k -n ${vm_cs} -c ${CLOUD_NAME}
 #done
 
-for vm_name in $(nova list --status ERROR --minimal 2> /dev/null | tail -n +4 | head -n -1 | awk '{print $4}'); do
-    echo "Terminating VM instance ${vm_name} in ERROR state"
-    vm_cs=$(cloud_status -m | grep ${vm_name} | awk '{print $1}')
-    if [ -n "${vm_cs}" ]; then
-	cloud_admin -k -n ${vm_cs} -c ${CLOUD_NAME}
+for vm_nova_name in $(openstack server list --status ERROR -f value -c Name 2> /dev/null); do
+    msg "deleting VM instance ${vm_nova_name} in ERROR state"
+    vm_cs_name=$(cloud_status -m | grep ${vm_nova_name} | awk '{print $1}')
+    if [[ -n "${vm_cs_name}" ]]; then
+	cloud_admin -k -n ${vm_cs_name} -c ${cloud}
     else
-	nova delete ${vm_name} 2> /dev/null
+	openstack server delete ${vm_nova_name} 2> /dev/null
     fi
 done
+
+sudo cloud_admin -e ${cloud}
+condor_release -a
