adapt to new cloud

diff --git a/manager/bin/canfar_submit b/manager/bin/canfar_submit
--- a/manager/bin/canfar_submit
+++ b/manager/bin/canfar_submit
@@ -1,24 +1,24 @@
 #!/bin/bash
 #
-# User script for submitting jobs. A wrapper for cansub,
+# User script for submitting jobs. A wrapper for canfar_translate_vm,
 # canfar_job_validate and condor_submit. Normally a user should
-# use cansub (without the --nopost option) so that the job goes
+# use canfar_translate_vm so that the job goes
 # through the web service. This script avoids the web service and can
 # submit jobs directly on the head node for testing purposes.
 
 EXEC_NAME=$(basename $0 .${0##*.})
-EXEC_VERSION=0.3.1
+EXEC_VERSION=0.3.4
 
 msg() {
     echo -e " >> ${EXEC_NAME}: $1"
 }
 
 warn() {
-    echo -e " >> ${EXEC_NAME} WARNING: $1"
+    echo -e " ## WARNING ${EXEC_NAME}: $1"
 }
 
 die() {
-    echo -e " >> ${EXEC_NAME} ERROR: $1" 1>&2
+    echo -e " !! ERROR ${EXEC_NAME}: $1" 1>&2
     exit 1
 }
 
@@ -31,16 +31,10 @@ Submit a CANFAR batch job
   VM_FLAVOR      OpenStack VM resource flavor used to process jobs
 
   -c, --cert=<path>         specify path for proxy to access VOSpace (default: ${HOME}/.ssl/cadcproxy.pem)
+  -u, --user=<username>     specify user to run the jobs on the VM (default: automatically detected)
   -h, --help                display help and exit
   -v, --version             output version information and exit
   -V, --verbose             verbose mode for debugging
-
-Import environment variables to be set:
-  OS_AUTH_URL
-  OS_TENANT_ID
-  OS_TENANT_NAME
-  OS_USERNAME
-  OS_PASSWORD
 "
     exit
 }
@@ -49,8 +43,9 @@ VERBOSE=
 
 # Store all options
 OPTS=$(getopt \
-    -o c:hvV \
+    -o c:u:hvV \
     -l cert: \
+    -l user: \
     -l help \
     -l version \
     -l verbose \
@@ -64,6 +59,7 @@ CERT_USER=
 while true; do
     case "$1" in
 	-c | --cert) CERT_USER="--cert=${2##=}"; shift ;;
+	-u | --user) JOB_USER="--submitter=${2##=}"; shift ;;	
 	-h | --help) usage ;;
 	-v | --version) echo ${EXEC_VERSION}; exit ;;
 	-V | --verbose) VERBOSE="--verbose" ;;
@@ -81,46 +77,52 @@ done
 JOB_FILE=$1
 VM_IMAGE=$2
 VM_FLAVOR=$3
+CM_IP="--cmip=$(hostname -I)"
 
 [[ -e ${JOB_FILE} ]] || die "HTCondor job submission file '${JOB_FILE}' does not exist"
 
 # Extract executable
-JOB_SCRIPT="$(grep '^[^#]*Executable\s*=' ${JOB_FILE} | cut -d= -f2 | awk '{print $1}')" \
-    || die "could not search for 'Executable' in ${JOB_FILE}"
+JOB_SCRIPT="$(grep -i '^[^#]*Executable\s*=' ${JOB_FILE} | cut -d= -f2 | awk '{print $1}')" \
+    || die "could not search for 'executable' in ${JOB_FILE}"
 
 [[ -z ${JOB_SCRIPT} ]] \
-    && die "could not extract 'Executable' from ${JOB_FILE}"
+    && die "could not extract 'executable' from ${JOB_FILE}"
 [[ -e ${JOB_SCRIPT} ]] \
-    || die "Executable '${JOB_SCRIPT}' extracted from ${JOB_FILE} does not exist on batch"
+    || die "executable '${JOB_SCRIPT}' extracted from ${JOB_FILE} does not exist on batch"
 
-if [[ -z ${OS_AUTH_URL} ]] || [[ -z ${OS_TENANT_ID} ]] || [[ -z ${OS_TENANT_NAME} ]] || \
-    [[ -z ${OS_USERNAME} ]] || [[ -z ${OS_PASSWORD} ]]; then
-    rcfiles=$(ls -1 ~/canfar-*-openrc.sh)
+if [[ -z ${OS_AUTH_URL} ]] || [[ -z ${OS_PROJECT_ID} ]] || [[ -z ${OS_PROJECT_NAME} ]] || \
+       [[ -z ${OS_USERNAME} ]] || [[ -z ${OS_PASSWORD} ]]; then
+    rcfiles=$(ls -1 ~/*-openrc.sh)
     die "OpenStack environment variables not set\n Try sourcing either:\n${rcfiles}"
 fi
 
-# Call cansub with --nopost simply to share the image and translate image
-# and flavor names to their IDs, which is what canfar_job_validate expects.
-[[ -n ${VERBOSE} ]] && msg "Running cansub ${JOB_FILE} ${VM_IMAGE} ${VM_FLAVOR} --nopost"
-VM_IMAGE_AND_FLAVOR_IDS=$(cansub ${JOB_FILE} ${VM_IMAGE} ${VM_FLAVOR} --nopost 2>&1) \
-    || die "cansub failed with the error below\n >> cansub ${VM_IMAGE_AND_FLAVOR_IDS}"
+# Share the image and translate image and flavor names to their IDs, which is what canfar_job_validate expects.
+[[ -n ${VERBOSE} ]] && msg "running canfar_translate_vm ${VM_IMAGE} ${VM_FLAVOR}"
+VM_IMAGE_AND_FLAVOR_IDS=$(canfar_translate_vm ${VM_IMAGE} ${VM_FLAVOR} 2>&1) \
+    || die "canfar_translate_vm failed with the error below\n >> canfar_translate_vm ${VM_IMAGE_AND_FLAVOR_IDS}"
 
 # big string for the job
-[[ -n ${VERBOSE} ]] && msg "Running canfar_job_validate ${CERT_USER} ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS}"
+[[ -n ${VERBOSE} ]] && msg "running canfar_job_validate ${CM_IP} ${CERT_USER} ${JOB_USER} ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS}"
 
-
-jobfile="/tmp/canfar-submit-${USER}-$$.job"
-error=$((canfar_job_validate ${CERT_USER} ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS} > ${jobfile}) 2>&1) \
+jobfile="/var/cache/canfar/condor/canfar_submit_${USER}_$$.jdl"
+error=$((canfar_job_validate ${CM_IP} ${CERT_USER} ${JOB_USER} ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS} > ${jobfile}) 2>&1) \
     || die "submission failed with the error below\n >> canfar_job_validate ${error}"
 
-#JOB=$(canfar_job_validate ${CERT_USER} ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS} 2>&1) \
+#JOB=$(canfar_job_validate ${CM_IP} ${CERT_USER} ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS} 2>&1) \
 #    || die "submission failed with the error below\n >> canfar_job_validate ${JOB}"
-
-[[ -n ${VERBOSE} ]] && msg "Running condor_submit ${jobfile}"
 #echo "${JOB}" | condor_submit || die "failed to submit job(s) to queue. Failed job below\n${JOB}"
-condor_submit ${jobfile} || die "failed to submit job(s) to queue. Failed job in ${jobfile}"
+
+cadc_cert ${VERBOSE} ${CERT}
+
 if [[ -n ${VERBOSE} ]]; then
-    msg "Successfully submitted job(s). Job file not removed."
+    msg "running condor_submit ${jobfile}"
+    tmp_condor_out="/tmp/condor_submit_$$.jdl"
+    condor_submit ${jobfile} > ${tmp_condor_out} || die "failed to submit job(s) to queue. Failed job in ${jobfile}"
+    msg "successfully submitted $(awk '/submitted/ {print $1}' ${tmp_condor_out}) job(s) with file: ${jobfile}"
+    mv ${jobfile} /var/cache/canfar/condor/canfar_submit_${USER}_$(awk '/submitted/ {print $6}' ${tmp_condor_out})jdl
+    cat ${tmp_condor_out}
+    rm ${tmp_condor_out}
 else
+    condor_submit ${jobfile} || die "failed to submit job(s) to queue. Failed job in ${jobfile}"
     rm -f ${jobfile}
 fi
