obsolete utils, but still keeping around

diff --git a/manager/bin/canfar_inject_cert b/manager/bin/canfar_inject_cert
--- a/manager/bin/canfar_inject_cert
+++ b/manager/bin/canfar_inject_cert
@@ -1,22 +1,22 @@
 #!/bin/bash
 #
-# Shell script to inject a CANFAR proxy cert into a HTCondor job submission file.
+# Shell script to inject a CADC proxy cert into a HTCondor job submission file.
 #
 
 EXEC_NAME=$(basename $0 .${0##*.})
-EXEC_VERSION=0.1.0
+EXEC_VERSION=0.1.2
 
-# Default path for CANFAR user X509 proxy cert
-CANFAR_CERT_PATH="${HOME}/.ssl/cadcproxy.pem"
+# Default path for CADC user X509 proxy cert
+CADC_CERT_PATH="${HOME}/.ssl/cadcproxy.pem"
 # min validation in days the cert has to be
-CANFAR_CERT_MIN_VALID=5
+CADC_CERT_MIN_VALID=5
 # max validation in days the cert will be
-CANFAR_CERT_MAX_VALID=15
-# cadc/canfar url to check a valid cert
-CANFAR_URL="www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca"
+CADC_CERT_MAX_VALID=15
+# cadc url to check a valid cert
+CADC_URL="www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca"
 
-# the canfar user for the proxy cert if needed
-CANFAR_USER="${USER}"
+# the CADC user for the proxy cert if needed
+CADC_USER="${USER}"
 
 # the hook script to rename the proxy cert
 CANFAR_CERT_HOOK_SCRIPT="canfar_condor_cert_hook"
@@ -26,7 +26,7 @@ msg() {
 }
 
 die() {
-    echo "ERROR ${EXEC_NAME}: $1" 1>&2
+    echo " !! ERROR ${EXEC_NAME}: $1" 1>&2
     exit 1
 }
 
@@ -34,8 +34,8 @@ usage() {
     echo $"Usage: ${EXEC_NAME} [OPTION] SUBFILE...SUBFILE
 Add the necessary cruft to inject proxy certificate.
 
-  -c, --cert          	    specify the CANFAR cert path to inject (default: ${CANFAR_CERT_PATH})
-  -u, --user          	    specify the CANFAR username to fetch the cert for (default: ${USER})
+  -c, --cert          	    specify the CADC cert path to inject (default: ${CADC_CERT_PATH})
+  -u, --user          	    specify the CADC username to fetch the cert for (default: ${USER})
   -h, --help                display help and exit
   -v, --version             output version information and exit
 
@@ -47,30 +47,30 @@ Add the necessary cruft to inject proxy certificate.
 # 1. use an existing cert
 # 2. use a .netrc file
 # 3. prompt user a password
-canfar_get_cert() {
+cadc_get_cert() {
     local days=$1
-    if [[ -e ${CANFAR_CERT_PATH} ]]; then
-	cadc-get-cert --quiet --days-valid=${days} --cert ${CANFAR_CERT_PATH} > /dev/null
-    elif grep -q ${CANFAR_URL}.*${CANFAR_USER} ${HOME}/.netrc 2> /dev/null; then
+    if [[ -e ${CADC_CERT_PATH} ]]; then
+	cadc-get-cert --quiet --days-valid=${days} --cert ${CADC_CERT_PATH} > /dev/null
+    elif grep -q ${CADC_URL}.*${CADC_USER} ${HOME}/.netrc 2> /dev/null; then
 	cadc-get-cert --quiet --days-valid=${days} --netrc-file > /dev/null
     else
-	cadc-get-cert --quiet --days-valid=${days} --user ${CANFAR_USER} > /dev/null
+	cadc-get-cert --quiet --days-valid=${days} --user ${CADC_USER} > /dev/null
     fi
 }
 
 # Check a proxy cert for minimum days of validity for processing
-canfar_check_cert() {
-    if [[ ! -e ${CANFAR_CERT_PATH} ]]; then
-	msg "did not find certificate in '${CANFAR_CERT_PATH}, prompting you for cadc username/password"
-	canfar_get_cert ${CANFAR_CERT_MAX_VALID} || die "could not get a valid certificate"
+cadc_check_cert() {
+    if [[ ! -e ${CADC_CERT_PATH} ]]; then
+	msg "did not find certificate in '${CADC_CERT_PATH}, prompting you for cadc username/password"
+	cadc_get_cert ${CADC_CERT_MAX_VALID} || die "could not get a valid certificate"
 	return
     fi
-    local last_day_valid="$(openssl x509 -in ${CANFAR_CERT_PATH} -enddate -noout | sed -e 's/notAfter=//')"
+    local last_day_valid="$(openssl x509 -in ${CADC_CERT_PATH} -enddate -noout | sed -e 's/notAfter=//')"
     local days_left=$(( ( $(date --date="${last_day_valid}" +%s) - $(date --date="${today}" +%s) ) / 86400 ))
-    msg "Your certificate is still valid for ${days_left} days"
-    if [[ ${days_left} -lt ${CANFAR_CERT_MIN_VALID} ]]; then
-	msg "Renewing certificate for ${CANFAR_CERT_MAX_VALID} days"
-	canfar_get_cert ${CANFAR_CERT_MAX_VALID} || die "could not renew proxy cert"
+    msg "proxy certificate is still valid for ${days_left} days"
+    if [[ ${days_left} -lt ${CADC_CERT_MIN_VALID} ]]; then
+	msg "renewing proxy certificate for ${CADC_CERT_MAX_VALID} days"
+	cadc_get_cert ${CADC_CERT_MAX_VALID} || die "could not renew proxy cert"
     fi
 }
 
@@ -111,8 +111,8 @@ eval set -- "${OPTS}"
 # Process options
 while true; do
     case "$1" in
-	-c | --cert) CANFAR_CERT_PATH=${2##=}; shift ;;
-	-u | --user) CANFAR_USER=${2##=}; shift ;;
+	-c | --cert) CADC_CERT_PATH=${2##=}; shift ;;
+	-u | --user) CADC_USER=${2##=}; shift ;;
 	-h | --help) usage ;;
 	-V | --version) echo ${EXEC_VERSION}; exit ;;
 	--)  shift; break ;; # no more options
@@ -123,13 +123,13 @@ done
 
 subfile=$1
 
-canfar_check_cert
+cadc_check_cert
 
 condor_keyval_replace_or_append \
     "should_transfer_files" "yes" \
     ${subfile} 
 condor_keyval_replace_or_append_many \
-    "transfer_input_files" "${CANFAR_CERT_PATH},${CANFAR_CERT_HOOK_SCRIPT}" \
+    "transfer_input_files" "${CADC_CERT_PATH},${CANFAR_CERT_HOOK_SCRIPT}" \
     ${subfile} 
 
 # condor will only transfer files to the exec directory
@@ -139,5 +139,5 @@ condor_keyval_replace_or_append \
     "+PreCmd" "\"$(basename ${CANFAR_CERT_HOOK_SCRIPT})\"" \
     ${subfile} 
 condor_keyval_replace_or_append \
-    "+PreArguments" "\"$(basename ${CANFAR_CERT_PATH})\"" \
+    "+PreArguments" "\"$(basename ${CADC_CERT_PATH})\"" \
     ${subfile} 
